#!/usr/local/bin/php -f
<?php
if(!isset($argv[1])) die("Error: Must provide input\n");
unset($argv[0]);
$prompt = implode(" ",$argv);
require_once(__DIR__."/src/SmartGPT.php");
$smartgpt = new SmartGPT($prompt);
